# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from models.project_summary import ProjectSummary  # noqa: E501
from harbor.rest import ApiException


class TestProjectSummary(unittest.TestCase):
    """ProjectSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectSummary(self):
        """Test ProjectSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harbor.models.project_summary.ProjectSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
