# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from models.trigger_settings import TriggerSettings  # noqa: E501
from harbor.rest import ApiException


class TestTriggerSettings(unittest.TestCase):
    """TriggerSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTriggerSettings(self):
        """Test TriggerSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harbor.models.trigger_settings.TriggerSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
