# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from api.system_api import SystemApi  # noqa: E501
from harbor.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = api.system_api.SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_system_cve_whitelist_get(self):
        """Test case for system_cve_whitelist_get

        Get the system level whitelist of CVE.  # noqa: E501
        """
        pass

    def test_system_cve_whitelist_put(self):
        """Test case for system_cve_whitelist_put

        Update the system level whitelist of CVE.  # noqa: E501
        """
        pass

    def test_system_oidc_ping_post(self):
        """Test case for system_oidc_ping_post

        Test the OIDC endpoint.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
