# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from models.ping_registry import PingRegistry  # noqa: E501
from harbor.rest import ApiException


class TestPingRegistry(unittest.TestCase):
    """PingRegistry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPingRegistry(self):
        """Test PingRegistry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harbor.models.ping_registry.PingRegistry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
