# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from harbor.models.robot_create_v1 import RobotCreateV1  # noqa: E501
from harbor.rest import ApiException


class TestRobotCreateV1(unittest.TestCase):
    """RobotCreateV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRobotCreateV1(self):
        """Test RobotCreateV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harbor.models.robot_create_v1.RobotCreateV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
