# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from api.project_api import ProjectApi  # noqa: E501
from harbor.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_logs(self):
        """Test case for get_logs

        Get recent logs of the projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
