# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from models.instance_update_resp import InstanceUpdateResp  # noqa: E501
from harbor.rest import ApiException


class TestInstanceUpdateResp(unittest.TestCase):
    """InstanceUpdateResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceUpdateResp(self):
        """Test InstanceUpdateResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harbor.models.instance_update_resp.InstanceUpdateResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
