# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import harbor
from harbor.models.project_metadata import ProjectMetadata  # noqa: E501
from harbor.rest import ApiException


class TestProjectMetadata(unittest.TestCase):
    """ProjectMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectMetadata(self):
        """Test ProjectMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harbor.models.project_metadata.ProjectMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
