# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GeneralInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'with_notary': 'bool',
        'with_clair': 'bool',
        'with_admiral': 'bool',
        'admiral_endpoint': 'str',
        'registry_url': 'str',
        'external_url': 'str',
        'auth_mode': 'str',
        'project_creation_restriction': 'str',
        'self_registration': 'bool',
        'has_ca_root': 'bool',
        'harbor_version': 'str',
        'next_scan_all': 'int',
        'clair_vulnerability_status': 'GeneralInfoClairVulnerabilityStatus'
    }

    attribute_map = {
        'with_notary': 'with_notary',
        'with_clair': 'with_clair',
        'with_admiral': 'with_admiral',
        'admiral_endpoint': 'admiral_endpoint',
        'registry_url': 'registry_url',
        'external_url': 'external_url',
        'auth_mode': 'auth_mode',
        'project_creation_restriction': 'project_creation_restriction',
        'self_registration': 'self_registration',
        'has_ca_root': 'has_ca_root',
        'harbor_version': 'harbor_version',
        'next_scan_all': 'next_scan_all',
        'clair_vulnerability_status': 'clair_vulnerability_status'
    }

    def __init__(self, with_notary=None, with_clair=None, with_admiral=None, admiral_endpoint=None, registry_url=None, external_url=None, auth_mode=None, project_creation_restriction=None, self_registration=None, has_ca_root=None, harbor_version=None, next_scan_all=None, clair_vulnerability_status=None):  # noqa: E501
        """GeneralInfo - a model defined in Swagger"""  # noqa: E501
        self._with_notary = None
        self._with_clair = None
        self._with_admiral = None
        self._admiral_endpoint = None
        self._registry_url = None
        self._external_url = None
        self._auth_mode = None
        self._project_creation_restriction = None
        self._self_registration = None
        self._has_ca_root = None
        self._harbor_version = None
        self._next_scan_all = None
        self._clair_vulnerability_status = None
        self.discriminator = None
        if with_notary is not None:
            self.with_notary = with_notary
        if with_clair is not None:
            self.with_clair = with_clair
        if with_admiral is not None:
            self.with_admiral = with_admiral
        if admiral_endpoint is not None:
            self.admiral_endpoint = admiral_endpoint
        if registry_url is not None:
            self.registry_url = registry_url
        if external_url is not None:
            self.external_url = external_url
        if auth_mode is not None:
            self.auth_mode = auth_mode
        if project_creation_restriction is not None:
            self.project_creation_restriction = project_creation_restriction
        if self_registration is not None:
            self.self_registration = self_registration
        if has_ca_root is not None:
            self.has_ca_root = has_ca_root
        if harbor_version is not None:
            self.harbor_version = harbor_version
        if next_scan_all is not None:
            self.next_scan_all = next_scan_all
        if clair_vulnerability_status is not None:
            self.clair_vulnerability_status = clair_vulnerability_status

    @property
    def with_notary(self):
        """Gets the with_notary of this GeneralInfo.  # noqa: E501

        If the Harbor instance is deployed with nested notary.  # noqa: E501

        :return: The with_notary of this GeneralInfo.  # noqa: E501
        :rtype: bool
        """
        return self._with_notary

    @with_notary.setter
    def with_notary(self, with_notary):
        """Sets the with_notary of this GeneralInfo.

        If the Harbor instance is deployed with nested notary.  # noqa: E501

        :param with_notary: The with_notary of this GeneralInfo.  # noqa: E501
        :type: bool
        """

        self._with_notary = with_notary

    @property
    def with_clair(self):
        """Gets the with_clair of this GeneralInfo.  # noqa: E501

        If the Harbor instance is deployed with nested clair.  # noqa: E501

        :return: The with_clair of this GeneralInfo.  # noqa: E501
        :rtype: bool
        """
        return self._with_clair

    @with_clair.setter
    def with_clair(self, with_clair):
        """Sets the with_clair of this GeneralInfo.

        If the Harbor instance is deployed with nested clair.  # noqa: E501

        :param with_clair: The with_clair of this GeneralInfo.  # noqa: E501
        :type: bool
        """

        self._with_clair = with_clair

    @property
    def with_admiral(self):
        """Gets the with_admiral of this GeneralInfo.  # noqa: E501

        If the Harbor instance is deployed with Admiral.  # noqa: E501

        :return: The with_admiral of this GeneralInfo.  # noqa: E501
        :rtype: bool
        """
        return self._with_admiral

    @with_admiral.setter
    def with_admiral(self, with_admiral):
        """Sets the with_admiral of this GeneralInfo.

        If the Harbor instance is deployed with Admiral.  # noqa: E501

        :param with_admiral: The with_admiral of this GeneralInfo.  # noqa: E501
        :type: bool
        """

        self._with_admiral = with_admiral

    @property
    def admiral_endpoint(self):
        """Gets the admiral_endpoint of this GeneralInfo.  # noqa: E501

        The url of the endpoint of admiral instance.  # noqa: E501

        :return: The admiral_endpoint of this GeneralInfo.  # noqa: E501
        :rtype: str
        """
        return self._admiral_endpoint

    @admiral_endpoint.setter
    def admiral_endpoint(self, admiral_endpoint):
        """Sets the admiral_endpoint of this GeneralInfo.

        The url of the endpoint of admiral instance.  # noqa: E501

        :param admiral_endpoint: The admiral_endpoint of this GeneralInfo.  # noqa: E501
        :type: str
        """

        self._admiral_endpoint = admiral_endpoint

    @property
    def registry_url(self):
        """Gets the registry_url of this GeneralInfo.  # noqa: E501

        The url of registry against which the docker command should be issued.  # noqa: E501

        :return: The registry_url of this GeneralInfo.  # noqa: E501
        :rtype: str
        """
        return self._registry_url

    @registry_url.setter
    def registry_url(self, registry_url):
        """Sets the registry_url of this GeneralInfo.

        The url of registry against which the docker command should be issued.  # noqa: E501

        :param registry_url: The registry_url of this GeneralInfo.  # noqa: E501
        :type: str
        """

        self._registry_url = registry_url

    @property
    def external_url(self):
        """Gets the external_url of this GeneralInfo.  # noqa: E501

        The external URL of Harbor, with protocol.  # noqa: E501

        :return: The external_url of this GeneralInfo.  # noqa: E501
        :rtype: str
        """
        return self._external_url

    @external_url.setter
    def external_url(self, external_url):
        """Sets the external_url of this GeneralInfo.

        The external URL of Harbor, with protocol.  # noqa: E501

        :param external_url: The external_url of this GeneralInfo.  # noqa: E501
        :type: str
        """

        self._external_url = external_url

    @property
    def auth_mode(self):
        """Gets the auth_mode of this GeneralInfo.  # noqa: E501

        The auth mode of current Harbor instance.  # noqa: E501

        :return: The auth_mode of this GeneralInfo.  # noqa: E501
        :rtype: str
        """
        return self._auth_mode

    @auth_mode.setter
    def auth_mode(self, auth_mode):
        """Sets the auth_mode of this GeneralInfo.

        The auth mode of current Harbor instance.  # noqa: E501

        :param auth_mode: The auth_mode of this GeneralInfo.  # noqa: E501
        :type: str
        """

        self._auth_mode = auth_mode

    @property
    def project_creation_restriction(self):
        """Gets the project_creation_restriction of this GeneralInfo.  # noqa: E501

        Indicate who can create projects, it could be 'adminonly' or 'everyone'.  # noqa: E501

        :return: The project_creation_restriction of this GeneralInfo.  # noqa: E501
        :rtype: str
        """
        return self._project_creation_restriction

    @project_creation_restriction.setter
    def project_creation_restriction(self, project_creation_restriction):
        """Sets the project_creation_restriction of this GeneralInfo.

        Indicate who can create projects, it could be 'adminonly' or 'everyone'.  # noqa: E501

        :param project_creation_restriction: The project_creation_restriction of this GeneralInfo.  # noqa: E501
        :type: str
        """

        self._project_creation_restriction = project_creation_restriction

    @property
    def self_registration(self):
        """Gets the self_registration of this GeneralInfo.  # noqa: E501

        Indicate whether the Harbor instance enable user to register himself.  # noqa: E501

        :return: The self_registration of this GeneralInfo.  # noqa: E501
        :rtype: bool
        """
        return self._self_registration

    @self_registration.setter
    def self_registration(self, self_registration):
        """Sets the self_registration of this GeneralInfo.

        Indicate whether the Harbor instance enable user to register himself.  # noqa: E501

        :param self_registration: The self_registration of this GeneralInfo.  # noqa: E501
        :type: bool
        """

        self._self_registration = self_registration

    @property
    def has_ca_root(self):
        """Gets the has_ca_root of this GeneralInfo.  # noqa: E501

        Indicate whether there is a ca root cert file ready for download in the file system.  # noqa: E501

        :return: The has_ca_root of this GeneralInfo.  # noqa: E501
        :rtype: bool
        """
        return self._has_ca_root

    @has_ca_root.setter
    def has_ca_root(self, has_ca_root):
        """Sets the has_ca_root of this GeneralInfo.

        Indicate whether there is a ca root cert file ready for download in the file system.  # noqa: E501

        :param has_ca_root: The has_ca_root of this GeneralInfo.  # noqa: E501
        :type: bool
        """

        self._has_ca_root = has_ca_root

    @property
    def harbor_version(self):
        """Gets the harbor_version of this GeneralInfo.  # noqa: E501

        The build version of Harbor.  # noqa: E501

        :return: The harbor_version of this GeneralInfo.  # noqa: E501
        :rtype: str
        """
        return self._harbor_version

    @harbor_version.setter
    def harbor_version(self, harbor_version):
        """Sets the harbor_version of this GeneralInfo.

        The build version of Harbor.  # noqa: E501

        :param harbor_version: The harbor_version of this GeneralInfo.  # noqa: E501
        :type: str
        """

        self._harbor_version = harbor_version

    @property
    def next_scan_all(self):
        """Gets the next_scan_all of this GeneralInfo.  # noqa: E501

        The UTC time in milliseconds, after which user can call scanAll API to scan all images.  # noqa: E501

        :return: The next_scan_all of this GeneralInfo.  # noqa: E501
        :rtype: int
        """
        return self._next_scan_all

    @next_scan_all.setter
    def next_scan_all(self, next_scan_all):
        """Sets the next_scan_all of this GeneralInfo.

        The UTC time in milliseconds, after which user can call scanAll API to scan all images.  # noqa: E501

        :param next_scan_all: The next_scan_all of this GeneralInfo.  # noqa: E501
        :type: int
        """

        self._next_scan_all = next_scan_all

    @property
    def clair_vulnerability_status(self):
        """Gets the clair_vulnerability_status of this GeneralInfo.  # noqa: E501


        :return: The clair_vulnerability_status of this GeneralInfo.  # noqa: E501
        :rtype: GeneralInfoClairVulnerabilityStatus
        """
        return self._clair_vulnerability_status

    @clair_vulnerability_status.setter
    def clair_vulnerability_status(self, clair_vulnerability_status):
        """Sets the clair_vulnerability_status of this GeneralInfo.


        :param clair_vulnerability_status: The clair_vulnerability_status of this GeneralInfo.  # noqa: E501
        :type: GeneralInfoClairVulnerabilityStatus
        """

        self._clair_vulnerability_status = clair_vulnerability_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeneralInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeneralInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
