# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ImmutableTagRule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'project_id': 'int',
        'tag_filter': 'str',
        'enabled': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'project_id': 'project_id',
        'tag_filter': 'tag_filter',
        'enabled': 'enabled'
    }

    def __init__(self, id=None, project_id=None, tag_filter=None, enabled=None):  # noqa: E501
        """ImmutableTagRule - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._project_id = None
        self._tag_filter = None
        self._enabled = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if project_id is not None:
            self.project_id = project_id
        if tag_filter is not None:
            self.tag_filter = tag_filter
        if enabled is not None:
            self.enabled = enabled

    @property
    def id(self):
        """Gets the id of this ImmutableTagRule.  # noqa: E501


        :return: The id of this ImmutableTagRule.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImmutableTagRule.


        :param id: The id of this ImmutableTagRule.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def project_id(self):
        """Gets the project_id of this ImmutableTagRule.  # noqa: E501


        :return: The project_id of this ImmutableTagRule.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ImmutableTagRule.


        :param project_id: The project_id of this ImmutableTagRule.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def tag_filter(self):
        """Gets the tag_filter of this ImmutableTagRule.  # noqa: E501


        :return: The tag_filter of this ImmutableTagRule.  # noqa: E501
        :rtype: str
        """
        return self._tag_filter

    @tag_filter.setter
    def tag_filter(self, tag_filter):
        """Sets the tag_filter of this ImmutableTagRule.


        :param tag_filter: The tag_filter of this ImmutableTagRule.  # noqa: E501
        :type: str
        """

        self._tag_filter = tag_filter

    @property
    def enabled(self):
        """Gets the enabled of this ImmutableTagRule.  # noqa: E501


        :return: The enabled of this ImmutableTagRule.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this ImmutableTagRule.


        :param enabled: The enabled of this ImmutableTagRule.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImmutableTagRule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImmutableTagRule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
