# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RepoSignature(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'str',
        'hashes': 'object'
    }

    attribute_map = {
        'tag': 'tag',
        'hashes': 'hashes'
    }

    def __init__(self, tag=None, hashes=None):  # noqa: E501
        """RepoSignature - a model defined in Swagger"""  # noqa: E501
        self._tag = None
        self._hashes = None
        self.discriminator = None
        if tag is not None:
            self.tag = tag
        if hashes is not None:
            self.hashes = hashes

    @property
    def tag(self):
        """Gets the tag of this RepoSignature.  # noqa: E501

        The tag of image.  # noqa: E501

        :return: The tag of this RepoSignature.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this RepoSignature.

        The tag of image.  # noqa: E501

        :param tag: The tag of this RepoSignature.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def hashes(self):
        """Gets the hashes of this RepoSignature.  # noqa: E501

        The JSON object of the hash of the image.  # noqa: E501

        :return: The hashes of this RepoSignature.  # noqa: E501
        :rtype: object
        """
        return self._hashes

    @hashes.setter
    def hashes(self, hashes):
        """Sets the hashes of this RepoSignature.

        The JSON object of the hash of the image.  # noqa: E501

        :param hashes: The hashes of this RepoSignature.  # noqa: E501
        :type: object
        """

        self._hashes = hashes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RepoSignature, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RepoSignature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
