# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Stats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'completed': 'int',
        'requester': 'str',
        'metrics': 'dict(str, int)'
    }

    attribute_map = {
        'total': 'total',
        'completed': 'completed',
        'requester': 'requester',
        'metrics': 'metrics'
    }

    def __init__(self, total=None, completed=None, requester=None, metrics=None):  # noqa: E501
        """Stats - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._completed = None
        self._requester = None
        self._metrics = None
        self.discriminator = None
        if total is not None:
            self.total = total
        if completed is not None:
            self.completed = completed
        if requester is not None:
            self.requester = requester
        if metrics is not None:
            self.metrics = metrics

    @property
    def total(self):
        """Gets the total of this Stats.  # noqa: E501

        The total number of scan processes triggered by the scan all action  # noqa: E501

        :return: The total of this Stats.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this Stats.

        The total number of scan processes triggered by the scan all action  # noqa: E501

        :param total: The total of this Stats.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def completed(self):
        """Gets the completed of this Stats.  # noqa: E501

        The number of the finished scan processes triggered by the scan all action  # noqa: E501

        :return: The completed of this Stats.  # noqa: E501
        :rtype: int
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this Stats.

        The number of the finished scan processes triggered by the scan all action  # noqa: E501

        :param completed: The completed of this Stats.  # noqa: E501
        :type: int
        """

        self._completed = completed

    @property
    def requester(self):
        """Gets the requester of this Stats.  # noqa: E501

        The requester identity which usually uses the ID of the scan all job  # noqa: E501

        :return: The requester of this Stats.  # noqa: E501
        :rtype: str
        """
        return self._requester

    @requester.setter
    def requester(self, requester):
        """Sets the requester of this Stats.

        The requester identity which usually uses the ID of the scan all job  # noqa: E501

        :param requester: The requester of this Stats.  # noqa: E501
        :type: str
        """

        self._requester = requester

    @property
    def metrics(self):
        """Gets the metrics of this Stats.  # noqa: E501

        The metrics data for the each status  # noqa: E501

        :return: The metrics of this Stats.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this Stats.

        The metrics data for the each status  # noqa: E501

        :param metrics: The metrics of this Stats.  # noqa: E501
        :type: dict(str, int)
        """

        self._metrics = metrics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Stats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Stats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
